export const faqData = [
    {
        question: "How does InstaHeadshots work?",
        answer: "InstaHeadshots uses your uploaded photos to build a personalized AI model that learns your unique facial features. With the help of our AI headshot generator, it creates stunning new headshots featuring a variety of poses, outfits, and backgrounds. For the best results, upload images from different angles and perspectives. Consistent features, like glasses or facial hair, will be reflected in the final headshots. Depending on your chosen package, AI training takes 2 to 60 minutes, and you’ll get an email notification when your headshots are ready to download!"
    },
    {
        question: "What kind of photos do I need to upload?",
        answer: "You’ll need to upload 10 images or selfies with different backgrounds, face angles, and lighting. The better the variety, the better your headshots will turn out."
    },
    {
        question: "How accurate are AI headshots?",
        answer: "AI-generated headshots are highly accurate and realistic when you provide varied, clear photos. Features like glasses, facial hair, and makeup that appear consistently in your photos will be reinforced in the final headshots. Despite being generated by AI, they are as realistic as a real studio photoshoot."
    },
    {
        question: "How long does it take to receive my headshots?",
        answer: "It usually takes about 60 minutes for the AI headshots to generate on the Starter pack. On Basic and Premium packs, it is significantly faster. You’ll receive an email notification as soon as they’re ready."
    }
];
